from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaPrincipal(object):
    def setupUi(self, telaPrincipal):
        telaPrincipal.setObjectName("telaPrincipal")
        telaPrincipal.resize(1873, 871)
        self.centralwidget = QtWidgets.QWidget(telaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gb_calculadoradeResistores = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_calculadoradeResistores.sizePolicy().hasHeightForWidth())
        self.gb_calculadoradeResistores.setSizePolicy(sizePolicy)
        self.gb_calculadoradeResistores.setTitle("")
        self.gb_calculadoradeResistores.setObjectName("gb_calculadoradeResistores")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gb_calculadoradeResistores)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.gb_calculadoradeResistores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addWidget(self.frame_12, 0, 0, 1, 2)
        self.tb_Curiosidades = QtWidgets.QTabWidget(self.frame_3)
        self.tb_Curiosidades.setObjectName("tb_Curiosidades")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/tabela_resistor.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_38.addWidget(self.label_3, 0, 0, 1, 1)
        self.tb_Curiosidades.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.frame_7 = QtWidgets.QFrame(self.tab_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/valores comerciais.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_41.addWidget(self.label_4, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border: 1px solid #000;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-color: transparent;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_42.addWidget(self.label_5, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_41.addWidget(self.frame_8, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.frame_7, 0, 0, 1, 1)
        self.tb_Curiosidades.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.tab_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.tab_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/icons/lei_de_ohm.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_43.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_14 = QtWidgets.QFrame(self.tab_7)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_7 = QtWidgets.QLabel(self.frame_14)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/icons/texto.png"))
        self.label_7.setObjectName("label_7")
        self.gridLayout_44.addWidget(self.label_7, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.frame_14)
        self.tb_Curiosidades.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.frame_15 = QtWidgets.QFrame(self.tab_8)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.label_10 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icons/icons/formula.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_46.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_12.addWidget(self.frame_19)
        self.gridLayout_45.addWidget(self.frame_15, 0, 0, 1, 1)
        self.tb_Curiosidades.addTab(self.tab_8, "")
        self.gridLayout_7.addWidget(self.tb_Curiosidades, 1, 1, 2, 1)
        self.tb_calculadoraResistores = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_calculadoraResistores.sizePolicy().hasHeightForWidth())
        self.tb_calculadoraResistores.setSizePolicy(sizePolicy)
        self.tb_calculadoraResistores.setObjectName("tb_calculadoraResistores")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_numero_1 = QtWidgets.QLabel(self.groupBox_11)
        self.label_numero_1.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_1.setObjectName("label_numero_1")
        self.verticalLayout_4.addWidget(self.label_numero_1)
        self.label_numero_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_numero_2.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_2.setObjectName("label_numero_2")
        self.verticalLayout_4.addWidget(self.label_numero_2)
        self.label_numero_3 = QtWidgets.QLabel(self.groupBox_11)
        self.label_numero_3.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_3.setObjectName("label_numero_3")
        self.verticalLayout_4.addWidget(self.label_numero_3)
        self.label_multiplicador = QtWidgets.QLabel(self.groupBox_11)
        self.label_multiplicador.setMaximumSize(QtCore.QSize(80, 25))
        self.label_multiplicador.setObjectName("label_multiplicador")
        self.verticalLayout_4.addWidget(self.label_multiplicador)
        self.label_tolerancia = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tolerancia.sizePolicy().hasHeightForWidth())
        self.label_tolerancia.setSizePolicy(sizePolicy)
        self.label_tolerancia.setMaximumSize(QtCore.QSize(80, 25))
        self.label_tolerancia.setObjectName("label_tolerancia")
        self.verticalLayout_4.addWidget(self.label_tolerancia)
        spacerItem1 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout_47.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_39.setContentsMargins(-1, 3, -1, 0)
        self.gridLayout_39.setVerticalSpacing(9)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.cb_faixa_3 = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_3.sizePolicy().hasHeightForWidth())
        self.cb_faixa_3.setSizePolicy(sizePolicy)
        self.cb_faixa_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_3.setObjectName("cb_faixa_3")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.setItemText(0, "")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.cb_faixa_3.addItem("")
        self.gridLayout_39.addWidget(self.cb_faixa_3, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_39.addItem(spacerItem2, 0, 0, 1, 1)
        self.cb_faixa_1 = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_1.sizePolicy().hasHeightForWidth())
        self.cb_faixa_1.setSizePolicy(sizePolicy)
        self.cb_faixa_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_1.setObjectName("cb_faixa_1")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.setItemText(0, "")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.cb_faixa_1.addItem("")
        self.gridLayout_39.addWidget(self.cb_faixa_1, 1, 0, 1, 1)
        self.cb_faixa_2 = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_2.sizePolicy().hasHeightForWidth())
        self.cb_faixa_2.setSizePolicy(sizePolicy)
        self.cb_faixa_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_2.setObjectName("cb_faixa_2")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.setItemText(0, "")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.cb_faixa_2.addItem("")
        self.gridLayout_39.addWidget(self.cb_faixa_2, 2, 0, 1, 1)
        self.cb_multiplicador = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_multiplicador.sizePolicy().hasHeightForWidth())
        self.cb_multiplicador.setSizePolicy(sizePolicy)
        self.cb_multiplicador.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_multiplicador.setObjectName("cb_multiplicador")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.setItemText(0, "")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.cb_multiplicador.addItem("")
        self.gridLayout_39.addWidget(self.cb_multiplicador, 4, 0, 1, 1)
        self.cb_tolerancia = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_tolerancia.sizePolicy().hasHeightForWidth())
        self.cb_tolerancia.setSizePolicy(sizePolicy)
        self.cb_tolerancia.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_tolerancia.setObjectName("cb_tolerancia")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.setItemText(0, "")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.cb_tolerancia.addItem("")
        self.gridLayout_39.addWidget(self.cb_tolerancia, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_39.addItem(spacerItem3, 6, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btn_calcularResistor = QtWidgets.QPushButton(self.frame_5)
        self.btn_calcularResistor.setObjectName("btn_calcularResistor")
        self.gridLayout_10.addWidget(self.btn_calcularResistor, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.frame_5, 1, 0, 1, 2)
        self.frame_27 = QtWidgets.QFrame(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_resultadoValorresistor = QtWidgets.QLabel(self.frame_27)
        self.label_resultadoValorresistor.setMaximumSize(QtCore.QSize(80, 25))
        self.label_resultadoValorresistor.setObjectName("label_resultadoValorresistor")
        self.gridLayout_22.addWidget(self.label_resultadoValorresistor, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_47.addWidget(self.frame_27, 2, 0, 1, 2)
        self.tb_calculadoraResistores.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem5)
        self.label_numero_4 = QtWidgets.QLabel(self.groupBox_13)
        self.label_numero_4.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_4.setObjectName("label_numero_4")
        self.verticalLayout_13.addWidget(self.label_numero_4)
        self.label_numero_5 = QtWidgets.QLabel(self.groupBox_13)
        self.label_numero_5.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_5.setObjectName("label_numero_5")
        self.verticalLayout_13.addWidget(self.label_numero_5)
        self.label_numero_6 = QtWidgets.QLabel(self.groupBox_13)
        self.label_numero_6.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_6.setObjectName("label_numero_6")
        self.verticalLayout_13.addWidget(self.label_numero_6)
        self.label_numero_7 = QtWidgets.QLabel(self.groupBox_13)
        self.label_numero_7.setMaximumSize(QtCore.QSize(80, 25))
        self.label_numero_7.setObjectName("label_numero_7")
        self.verticalLayout_13.addWidget(self.label_numero_7)
        self.label_multiplicador_2 = QtWidgets.QLabel(self.groupBox_13)
        self.label_multiplicador_2.setMaximumSize(QtCore.QSize(80, 25))
        self.label_multiplicador_2.setObjectName("label_multiplicador_2")
        self.verticalLayout_13.addWidget(self.label_multiplicador_2)
        self.label_tolerancia_2 = QtWidgets.QLabel(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tolerancia_2.sizePolicy().hasHeightForWidth())
        self.label_tolerancia_2.setSizePolicy(sizePolicy)
        self.label_tolerancia_2.setMaximumSize(QtCore.QSize(80, 25))
        self.label_tolerancia_2.setObjectName("label_tolerancia_2")
        self.verticalLayout_13.addWidget(self.label_tolerancia_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem6)
        self.gridLayout_51.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem7)
        self.cb_faixa_1a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_1a.sizePolicy().hasHeightForWidth())
        self.cb_faixa_1a.setSizePolicy(sizePolicy)
        self.cb_faixa_1a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_1a.setObjectName("cb_faixa_1a")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.setItemText(0, "")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.cb_faixa_1a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_faixa_1a)
        self.cb_faixa_2a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_2a.sizePolicy().hasHeightForWidth())
        self.cb_faixa_2a.setSizePolicy(sizePolicy)
        self.cb_faixa_2a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_2a.setObjectName("cb_faixa_2a")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.setItemText(0, "")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.cb_faixa_2a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_faixa_2a)
        self.cb_faixa_3a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_3a.sizePolicy().hasHeightForWidth())
        self.cb_faixa_3a.setSizePolicy(sizePolicy)
        self.cb_faixa_3a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_3a.setObjectName("cb_faixa_3a")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.setItemText(0, "")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.cb_faixa_3a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_faixa_3a)
        self.cb_faixa_4a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_faixa_4a.sizePolicy().hasHeightForWidth())
        self.cb_faixa_4a.setSizePolicy(sizePolicy)
        self.cb_faixa_4a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_faixa_4a.setObjectName("cb_faixa_4a")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.setItemText(0, "")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.cb_faixa_4a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_faixa_4a)
        self.cb_multiplicador_1a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_multiplicador_1a.sizePolicy().hasHeightForWidth())
        self.cb_multiplicador_1a.setSizePolicy(sizePolicy)
        self.cb_multiplicador_1a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_multiplicador_1a.setObjectName("cb_multiplicador_1a")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.setItemText(0, "")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.cb_multiplicador_1a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_multiplicador_1a)
        self.cb_tolerancia_1a = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_tolerancia_1a.sizePolicy().hasHeightForWidth())
        self.cb_tolerancia_1a.setSizePolicy(sizePolicy)
        self.cb_tolerancia_1a.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cb_tolerancia_1a.setObjectName("cb_tolerancia_1a")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.setItemText(0, "")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.cb_tolerancia_1a.addItem("")
        self.verticalLayout_14.addWidget(self.cb_tolerancia_1a)
        spacerItem8 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem8)
        self.gridLayout_51.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.btn_calcularResistor_2 = QtWidgets.QPushButton(self.frame_28)
        self.btn_calcularResistor_2.setObjectName("btn_calcularResistor_2")
        self.gridLayout_49.addWidget(self.btn_calcularResistor_2, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.frame_28, 1, 0, 1, 2)
        self.frame_40 = QtWidgets.QFrame(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_40.sizePolicy().hasHeightForWidth())
        self.frame_40.setSizePolicy(sizePolicy)
        self.frame_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.frame_40)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.label_resultadoValorresistor_2 = QtWidgets.QLabel(self.frame_40)
        self.label_resultadoValorresistor_2.setMaximumSize(QtCore.QSize(80, 25))
        self.label_resultadoValorresistor_2.setObjectName("label_resultadoValorresistor_2")
        self.gridLayout_50.addWidget(self.label_resultadoValorresistor_2, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_50.addItem(spacerItem9, 0, 1, 1, 1)
        self.gridLayout_51.addWidget(self.frame_40, 2, 0, 1, 2)
        self.tb_calculadoraResistores.addTab(self.tab_10, "")
        self.gridLayout_7.addWidget(self.tb_calculadoraResistores, 1, 0, 2, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gb_calculadoradeResistores, 0, 0, 1, 1)
        self.tb_ferramentas = QtWidgets.QTabWidget(self.frame_2)
        self.tb_ferramentas.setObjectName("tb_ferramentas")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_21 = QtWidgets.QFrame(self.frame_9)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_resultadoTensaoresultante = QtWidgets.QLabel(self.frame_21)
        self.label_resultadoTensaoresultante.setMaximumSize(QtCore.QSize(100, 25))
        self.label_resultadoTensaoresultante.setObjectName("label_resultadoTensaoresultante")
        self.gridLayout_17.addWidget(self.label_resultadoTensaoresultante, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem10, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_21, 1, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.frame_9)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btn_tensaoResultante = QtWidgets.QPushButton(self.frame_22)
        self.btn_tensaoResultante.setObjectName("btn_tensaoResultante")
        self.gridLayout_16.addWidget(self.btn_tensaoResultante, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_22, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_9, 1, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setContentsMargins(-1, 12, -1, 14)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_tensao_1 = QtWidgets.QLabel(self.groupBox_7)
        self.label_tensao_1.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensao_1.setFont(font)
        self.label_tensao_1.setObjectName("label_tensao_1")
        self.verticalLayout_2.addWidget(self.label_tensao_1)
        self.label_tensao_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_tensao_2.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensao_2.setFont(font)
        self.label_tensao_2.setObjectName("label_tensao_2")
        self.verticalLayout_2.addWidget(self.label_tensao_2)
        self.label_tensao_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_tensao_3.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensao_3.setFont(font)
        self.label_tensao_3.setObjectName("label_tensao_3")
        self.verticalLayout_2.addWidget(self.label_tensao_3)
        self.gridLayout_3.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(150, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(150, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_6, 0, 0, 1, 1)
        self.tb_ferramentas.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.tab_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_24 = QtWidgets.QFrame(self.frame_16)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.btn_correnteTotal = QtWidgets.QPushButton(self.frame_24)
        self.btn_correnteTotal.setObjectName("btn_correnteTotal")
        self.gridLayout_18.addWidget(self.btn_correnteTotal, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_16)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_resulatadoCorrentetotal = QtWidgets.QLabel(self.frame_23)
        self.label_resulatadoCorrentetotal.setMaximumSize(QtCore.QSize(80, 25))
        self.label_resulatadoCorrentetotal.setObjectName("label_resulatadoCorrentetotal")
        self.gridLayout_19.addWidget(self.label_resulatadoCorrentetotal, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem11, 0, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_23)
        self.gridLayout_13.addWidget(self.frame_16, 1, 0, 1, 2)
        self.groupBox_14 = QtWidgets.QGroupBox(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_corrente_1 = QtWidgets.QLabel(self.groupBox_14)
        self.label_corrente_1.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_corrente_1.setFont(font)
        self.label_corrente_1.setObjectName("label_corrente_1")
        self.verticalLayout_6.addWidget(self.label_corrente_1)
        self.label_corrente_2 = QtWidgets.QLabel(self.groupBox_14)
        self.label_corrente_2.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_corrente_2.setFont(font)
        self.label_corrente_2.setObjectName("label_corrente_2")
        self.verticalLayout_6.addWidget(self.label_corrente_2)
        self.label_corrente_3 = QtWidgets.QLabel(self.groupBox_14)
        self.label_corrente_3.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_corrente_3.setFont(font)
        self.label_corrente_3.setObjectName("label_corrente_3")
        self.verticalLayout_6.addWidget(self.label_corrente_3)
        self.gridLayout_13.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.entry_corrente_1 = QtWidgets.QLineEdit(self.groupBox_15)
        self.entry_corrente_1.setMaximumSize(QtCore.QSize(150, 22))
        self.entry_corrente_1.setObjectName("entry_corrente_1")
        self.verticalLayout.addWidget(self.entry_corrente_1)
        self.entry_corrente_2 = QtWidgets.QLineEdit(self.groupBox_15)
        self.entry_corrente_2.setMaximumSize(QtCore.QSize(150, 22))
        self.entry_corrente_2.setObjectName("entry_corrente_2")
        self.verticalLayout.addWidget(self.entry_corrente_2)
        self.entry_corrente_3 = QtWidgets.QLineEdit(self.groupBox_15)
        self.entry_corrente_3.setMaximumSize(QtCore.QSize(150, 22))
        self.entry_corrente_3.setObjectName("entry_corrente_3")
        self.verticalLayout.addWidget(self.entry_corrente_3)
        self.gridLayout_13.addWidget(self.groupBox_15, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.frame_13, 0, 0, 1, 1)
        self.tb_ferramentas.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.tab_3)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_25 = QtWidgets.QFrame(self.frame_20)
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.btn_resistenciaTotal = QtWidgets.QPushButton(self.frame_25)
        self.btn_resistenciaTotal.setObjectName("btn_resistenciaTotal")
        self.gridLayout_20.addWidget(self.btn_resistenciaTotal, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_20)
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_resistenciaTotal = QtWidgets.QLabel(self.frame_26)
        self.label_resistenciaTotal.setMaximumSize(QtCore.QSize(80, 25))
        self.label_resistenciaTotal.setObjectName("label_resistenciaTotal")
        self.gridLayout_21.addWidget(self.label_resistenciaTotal, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem12, 0, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_26)
        self.gridLayout_15.addWidget(self.frame_20, 1, 0, 1, 2)
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_tensaoInicial = QtWidgets.QLabel(self.groupBox_18)
        self.label_tensaoInicial.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensaoInicial.setFont(font)
        self.label_tensaoInicial.setObjectName("label_tensaoInicial")
        self.verticalLayout_8.addWidget(self.label_tensaoInicial)
        self.label_tensaoFinal = QtWidgets.QLabel(self.groupBox_18)
        self.label_tensaoFinal.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensaoFinal.setFont(font)
        self.label_tensaoFinal.setObjectName("label_tensaoFinal")
        self.verticalLayout_8.addWidget(self.label_tensaoFinal)
        self.gridLayout_15.addWidget(self.groupBox_18, 0, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_19.sizePolicy().hasHeightForWidth())
        self.groupBox_19.setSizePolicy(sizePolicy)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.entry_tensaoInicial = QtWidgets.QLineEdit(self.groupBox_19)
        self.entry_tensaoInicial.setMaximumSize(QtCore.QSize(150, 16777215))
        self.entry_tensaoInicial.setObjectName("entry_tensaoInicial")
        self.verticalLayout_7.addWidget(self.entry_tensaoInicial)
        self.entry_tensaoFinal = QtWidgets.QLineEdit(self.groupBox_19)
        self.entry_tensaoFinal.setMaximumSize(QtCore.QSize(150, 16777215))
        self.entry_tensaoFinal.setObjectName("entry_tensaoFinal")
        self.verticalLayout_7.addWidget(self.entry_tensaoFinal)
        self.gridLayout_15.addWidget(self.groupBox_19, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame_17, 0, 0, 1, 1)
        self.tb_ferramentas.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_24.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_29 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_25.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.frame_32 = QtWidgets.QFrame(self.frame_29)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_32.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_32)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.label_2 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_37.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_25.addWidget(self.frame_32, 0, 0, 1, 2)
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_30)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_39 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.frame_39)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label = QtWidgets.QLabel(self.frame_39)
        self.label.setObjectName("label")
        self.gridLayout_36.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_39)
        self.frame_37 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.frame_37)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_34.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_38)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.toolButton_20 = QtWidgets.QToolButton(self.frame_38)
        self.toolButton_20.setMinimumSize(QtCore.QSize(70, 25))
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout_35.addWidget(self.toolButton_20, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_38)
        self.gridLayout_33.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_30, 1, 0, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_31.sizePolicy().hasHeightForWidth())
        self.frame_31.setSizePolicy(sizePolicy)
        self.frame_31.setMinimumSize(QtCore.QSize(230, 0))
        self.frame_31.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_27.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.groupBox = QtWidgets.QGroupBox(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 306))
        self.groupBox.setMaximumSize(QtCore.QSize(223, 300))
        self.groupBox.setStyleSheet("background-color: rgb(14, 191, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_26.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.frame_33 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setMinimumSize(QtCore.QSize(200, 280))
        self.frame_33.setMaximumSize(QtCore.QSize(200, 288))
        self.frame_33.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_33)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_33)
        self.lcdNumber.setMaximumSize(QtCore.QSize(210, 35))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_31.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_34.sizePolicy().hasHeightForWidth())
        self.frame_34.setSizePolicy(sizePolicy)
        self.frame_34.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_34.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_34)
        self.gridLayout_29.setVerticalSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_35.sizePolicy().hasHeightForWidth())
        self.frame_35.setSizePolicy(sizePolicy)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 214))
        self.frame_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_35)
        self.gridLayout_30.setContentsMargins(2, -1, 9, -1)
        self.gridLayout_30.setHorizontalSpacing(7)
        self.gridLayout_30.setVerticalSpacing(3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_8.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_30.addWidget(self.toolButton_8, 1, 3, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_5.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_30.addWidget(self.toolButton_5, 2, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame_35)
        self.toolButton.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_30.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_12.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout_30.addWidget(self.toolButton_12, 2, 3, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_3.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_30.addWidget(self.toolButton_3, 1, 2, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_6.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_30.addWidget(self.toolButton_6, 0, 2, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_7.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_7.setText("")
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_30.addWidget(self.toolButton_7, 0, 3, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_11.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout_30.addWidget(self.toolButton_11, 1, 0, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_9.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_30.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_4.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_30.addWidget(self.toolButton_4, 2, 1, 1, 1)
        self.toolButton_15 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_15.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout_30.addWidget(self.toolButton_15, 3, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_2.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_30.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_10.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout_30.addWidget(self.toolButton_10, 0, 1, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_14.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout_30.addWidget(self.toolButton_14, 3, 0, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_16.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout_30.addWidget(self.toolButton_16, 3, 2, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(self.frame_35)
        self.toolButton_17.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout_30.addWidget(self.toolButton_17, 3, 3, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        self.frame_36.setMinimumSize(QtCore.QSize(162, 42))
        self.frame_36.setMaximumSize(QtCore.QSize(162, 62))
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_36)
        self.gridLayout_32.setContentsMargins(0, 0, 9, 5)
        self.gridLayout_32.setHorizontalSpacing(5)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.toolButton_13 = QtWidgets.QToolButton(self.frame_36)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(76)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.toolButton_13.sizePolicy().hasHeightForWidth())
        self.toolButton_13.setSizePolicy(sizePolicy)
        self.toolButton_13.setMinimumSize(QtCore.QSize(76, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.toolButton_13.setFont(font)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout_32.addWidget(self.toolButton_13, 0, 2, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(self.frame_36)
        self.toolButton_18.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout_32.addWidget(self.toolButton_18, 0, 1, 1, 1)
        self.toolButton_19 = QtWidgets.QToolButton(self.frame_36)
        self.toolButton_19.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout_32.addWidget(self.toolButton_19, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.frame_36, 4, 0, 1, 4)
        self.gridLayout_29.addWidget(self.frame_35, 1, 0, 1, 1)
        self.gridLayout_31.addWidget(self.frame_34, 1, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_33, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_31, 1, 1, 1, 1)
        self.gridLayout_24.addWidget(self.frame_29, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tb_ferramentas.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tb_ferramentas, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        telaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(telaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1873, 21))
        self.menubar.setObjectName("menubar")
        self.menuFerramentas = QtWidgets.QMenu(self.menubar)
        self.menuFerramentas.setObjectName("menuFerramentas")
        telaPrincipal.setMenuBar(self.menubar)
        self.actionCatalogoSMD = QtWidgets.QAction(telaPrincipal)
        self.actionCatalogoSMD.setObjectName("actionCatalogoSMD")
        self.actionCatalagoCapacitoresSMD = QtWidgets.QAction(telaPrincipal)
        self.actionCatalagoCapacitoresSMD.setObjectName("actionCatalagoCapacitoresSMD")
        self.actionCatalogoCPU = QtWidgets.QAction(telaPrincipal)
        self.actionCatalogoCPU.setObjectName("actionCatalogoCPU")
        self.actionCatalogoMCU = QtWidgets.QAction(telaPrincipal)
        self.actionCatalogoMCU.setObjectName("actionCatalogoMCU")
        self.actionCatalogoGPU = QtWidgets.QAction(telaPrincipal)
        self.actionCatalogoGPU.setObjectName("actionCatalogoGPU")
        self.menuFerramentas.addAction(self.actionCatalogoSMD)
        self.menuFerramentas.addAction(self.actionCatalagoCapacitoresSMD)
        self.menuFerramentas.addAction(self.actionCatalogoCPU)
        self.menuFerramentas.addAction(self.actionCatalogoMCU)
        self.menuFerramentas.addAction(self.actionCatalogoGPU)
        self.menubar.addAction(self.menuFerramentas.menuAction())

        self.retranslateUi(telaPrincipal)
        self.tb_Curiosidades.setCurrentIndex(3)
        self.tb_calculadoraResistores.setCurrentIndex(1)
        self.tb_ferramentas.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(telaPrincipal)

    def retranslateUi(self, telaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        telaPrincipal.setWindowTitle(_translate("telaPrincipal", "Calculos para Eletrônica"))
        self.label_8.setText(_translate("telaPrincipal", "Calculos para Eletrônica"))
        self.label_9.setText(_translate("telaPrincipal", "Tabela de cores dos Resistores"))
        self.tb_Curiosidades.setTabText(self.tb_Curiosidades.indexOf(self.tab_5), _translate("telaPrincipal", "Tabela de Resistores"))
        self.label_5.setText(_translate("telaPrincipal", "Valores Comerciais de Filme de Carbono"))
        self.tb_Curiosidades.setTabText(self.tb_Curiosidades.indexOf(self.tab_6), _translate("telaPrincipal", "Tabela Resistores SMD"))
        self.tb_Curiosidades.setTabText(self.tb_Curiosidades.indexOf(self.tab_7), _translate("telaPrincipal", "Lei de Ohm"))
        self.tb_Curiosidades.setTabText(self.tb_Curiosidades.indexOf(self.tab_8), _translate("telaPrincipal", "Fómula lei de Ohm"))
        self.label_numero_1.setText(_translate("telaPrincipal", "1° Número:"))
        self.label_numero_2.setText(_translate("telaPrincipal", "2° Número:"))
        self.label_numero_3.setText(_translate("telaPrincipal", "3° Número:"))
        self.label_multiplicador.setText(_translate("telaPrincipal", "Multiplicador:"))
        self.label_tolerancia.setText(_translate("telaPrincipal", "Tolerância:"))
        self.cb_faixa_3.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_3.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_3.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_3.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_3.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_3.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_3.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_3.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_3.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_3.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_3.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_3.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_3.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_3.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_faixa_1.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_1.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_1.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_1.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_1.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_1.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_1.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_1.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_1.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_1.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_1.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_1.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_1.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_1.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_faixa_2.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_2.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_2.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_2.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_2.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_2.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_2.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_2.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_2.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_2.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_2.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_2.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_2.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_2.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_multiplicador.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_multiplicador.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_multiplicador.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_multiplicador.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_multiplicador.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_multiplicador.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_multiplicador.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_multiplicador.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_multiplicador.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_multiplicador.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_multiplicador.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_multiplicador.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_multiplicador.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_multiplicador.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_tolerancia.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_tolerancia.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_tolerancia.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_tolerancia.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_tolerancia.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_tolerancia.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_tolerancia.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_tolerancia.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_tolerancia.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_tolerancia.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_tolerancia.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_tolerancia.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_tolerancia.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_tolerancia.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.btn_calcularResistor.setText(_translate("telaPrincipal", "Calcular Resistor"))
        self.label_resultadoValorresistor.setText(_translate("telaPrincipal", "Resultado:"))
        self.tb_calculadoraResistores.setTabText(self.tb_calculadoraResistores.indexOf(self.tab_9), _translate("telaPrincipal", "Calculadora de Resistores"))
        self.label_numero_4.setText(_translate("telaPrincipal", "1° Número:"))
        self.label_numero_5.setText(_translate("telaPrincipal", "2° Número:"))
        self.label_numero_6.setText(_translate("telaPrincipal", "3° Número:"))
        self.label_numero_7.setText(_translate("telaPrincipal", "4° Número:"))
        self.label_multiplicador_2.setText(_translate("telaPrincipal", "Multiplicador:"))
        self.label_tolerancia_2.setText(_translate("telaPrincipal", "Tolerância:"))
        self.cb_faixa_1a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_1a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_1a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_1a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_1a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_1a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_1a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_1a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_1a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_1a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_1a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_1a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_1a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_1a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_faixa_2a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_2a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_2a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_2a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_2a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_2a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_2a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_2a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_2a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_2a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_2a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_2a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_2a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_2a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_faixa_3a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_3a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_3a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_3a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_3a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_3a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_3a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_3a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_3a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_3a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_3a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_3a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_3a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_3a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_faixa_4a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_faixa_4a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_faixa_4a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_faixa_4a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_faixa_4a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_faixa_4a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_faixa_4a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_faixa_4a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_faixa_4a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_4a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_faixa_4a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_faixa_4a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_faixa_4a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_faixa_4a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_multiplicador_1a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_multiplicador_1a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_multiplicador_1a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_multiplicador_1a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_multiplicador_1a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_multiplicador_1a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_multiplicador_1a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_multiplicador_1a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_multiplicador_1a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_multiplicador_1a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_multiplicador_1a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_multiplicador_1a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_multiplicador_1a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_multiplicador_1a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.cb_tolerancia_1a.setItemText(1, _translate("telaPrincipal", "Preto "))
        self.cb_tolerancia_1a.setItemText(2, _translate("telaPrincipal", "Marrom"))
        self.cb_tolerancia_1a.setItemText(3, _translate("telaPrincipal", "Vermelho"))
        self.cb_tolerancia_1a.setItemText(4, _translate("telaPrincipal", "Laranja"))
        self.cb_tolerancia_1a.setItemText(5, _translate("telaPrincipal", "Amarelo"))
        self.cb_tolerancia_1a.setItemText(6, _translate("telaPrincipal", "Verde"))
        self.cb_tolerancia_1a.setItemText(7, _translate("telaPrincipal", "Azul"))
        self.cb_tolerancia_1a.setItemText(8, _translate("telaPrincipal", "Violeta"))
        self.cb_tolerancia_1a.setItemText(9, _translate("telaPrincipal", "Branco"))
        self.cb_tolerancia_1a.setItemText(10, _translate("telaPrincipal", "Cinza"))
        self.cb_tolerancia_1a.setItemText(11, _translate("telaPrincipal", "Branco"))
        self.cb_tolerancia_1a.setItemText(12, _translate("telaPrincipal", "Dourado"))
        self.cb_tolerancia_1a.setItemText(13, _translate("telaPrincipal", "Prateado"))
        self.cb_tolerancia_1a.setItemText(14, _translate("telaPrincipal", "Sem cor"))
        self.btn_calcularResistor_2.setText(_translate("telaPrincipal", "Calcular Resistor"))
        self.label_resultadoValorresistor_2.setText(_translate("telaPrincipal", "Resultado:"))
        self.tb_calculadoraResistores.setTabText(self.tb_calculadoraResistores.indexOf(self.tab_10), _translate("telaPrincipal", "Tab 2"))
        self.label_resultadoTensaoresultante.setText(_translate("telaPrincipal", "Resultado:"))
        self.btn_tensaoResultante.setText(_translate("telaPrincipal", "Tensão Resultante"))
        self.label_tensao_1.setText(_translate("telaPrincipal", "1° Tensão:"))
        self.label_tensao_2.setText(_translate("telaPrincipal", "2° Tensão:"))
        self.label_tensao_3.setText(_translate("telaPrincipal", "3° Tensão:"))
        self.tb_ferramentas.setTabText(self.tb_ferramentas.indexOf(self.tab), _translate("telaPrincipal", "Tensão Resultante"))
        self.btn_correnteTotal.setText(_translate("telaPrincipal", "Corrente Total"))
        self.label_resulatadoCorrentetotal.setText(_translate("telaPrincipal", "Resultado:"))
        self.label_corrente_1.setText(_translate("telaPrincipal", "1° Corrente:"))
        self.label_corrente_2.setText(_translate("telaPrincipal", "2° Corrente:"))
        self.label_corrente_3.setText(_translate("telaPrincipal", "3° Corrente:"))
        self.tb_ferramentas.setTabText(self.tb_ferramentas.indexOf(self.tab_2), _translate("telaPrincipal", "Corrente total"))
        self.btn_resistenciaTotal.setText(_translate("telaPrincipal", "Resistência Total"))
        self.label_resistenciaTotal.setText(_translate("telaPrincipal", "Resultado:"))
        self.label_tensaoInicial.setText(_translate("telaPrincipal", "Tensão Inicial:"))
        self.label_tensaoFinal.setText(_translate("telaPrincipal", "Tensão Final:"))
        self.tb_ferramentas.setTabText(self.tb_ferramentas.indexOf(self.tab_3), _translate("telaPrincipal", "Resistência Total"))
        self.label_2.setText(_translate("telaPrincipal", "Ferramentas do Sistema"))
        self.label.setText(_translate("telaPrincipal", "Anotações:"))
        self.toolButton_20.setText(_translate("telaPrincipal", "Salvar"))
        self.toolButton_8.setText(_translate("telaPrincipal", "/"))
        self.toolButton_5.setText(_translate("telaPrincipal", "4"))
        self.toolButton.setText(_translate("telaPrincipal", "%"))
        self.toolButton_12.setText(_translate("telaPrincipal", "x"))
        self.toolButton_3.setText(_translate("telaPrincipal", "9"))
        self.toolButton_6.setText(_translate("telaPrincipal", "C"))
        self.toolButton_11.setText(_translate("telaPrincipal", "7"))
        self.toolButton_9.setText(_translate("telaPrincipal", "6"))
        self.toolButton_4.setText(_translate("telaPrincipal", "5"))
        self.toolButton_15.setText(_translate("telaPrincipal", "2"))
        self.toolButton_2.setText(_translate("telaPrincipal", "8"))
        self.toolButton_10.setText(_translate("telaPrincipal", "CE"))
        self.toolButton_14.setText(_translate("telaPrincipal", "1"))
        self.toolButton_16.setText(_translate("telaPrincipal", "3"))
        self.toolButton_17.setText(_translate("telaPrincipal", "+"))
        self.toolButton_13.setText(_translate("telaPrincipal", "="))
        self.toolButton_18.setText(_translate("telaPrincipal", ","))
        self.toolButton_19.setText(_translate("telaPrincipal", "0"))
        self.tb_ferramentas.setTabText(self.tb_ferramentas.indexOf(self.tab_4), _translate("telaPrincipal", "Anotações"))
        self.menuFerramentas.setTitle(_translate("telaPrincipal", "Ferramentas"))
        self.actionCatalogoSMD.setText(_translate("telaPrincipal", "Catálogo de Resistores SMD"))
        self.actionCatalagoCapacitoresSMD.setText(_translate("telaPrincipal", "Catálago de Capacitores SMD"))
        self.actionCatalogoCPU.setText(_translate("telaPrincipal", "Catálogo de CPU"))
        self.actionCatalogoMCU.setText(_translate("telaPrincipal", "Catálogo de MCU"))
        self.actionCatalogoGPU.setText(_translate("telaPrincipal", "Catálogo de GPU"))
import iconsCalculos_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_telaPrincipal()
    ui.setupUi(telaPrincipal)
    telaPrincipal.show()
    sys.exit(app.exec_())
